# Generated by Django 4.2.3 on 2023-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_tax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='tax_number',
            field=models.CharField(max_length=255),
        ),
    ]
