# Generated by Django 4.2.3 on 2023-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='commercial_record',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
