# Generated by Django 4.2.3 on 2023-08-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_number',
        ),
    ]
