# Generated by Django 4.2.3 on 2023-09-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_due_time_invoice_invoice_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='show_due_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='show_invoice_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='show_time_of_supply',
            field=models.BooleanField(default=False),
        ),
    ]
